os: osx
osx_image: xcode14.1
language: swift
script: xcodebuild clean build test -project /Users/temur/Documents/Development/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO